version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://sakthivel19:Sakthivel-19@cluster0.yfwkf.mongodb.net/book_review_db?retryWrites=true&w=majority
